;---------------------------------------------------
; Programa: FAÇA UM PROGRAMA EM ASSEMBLY NEANDER QUE DETERMINA QUAL É A MAIOR DENTRE DUAS VARIÁVEIS POSITIVAS DE 8 BITS,
; REPRESENTADAS EM POSIÇÕES CONSECUTIVAS DA MEMÓRIA. A MAIOR DAS VARIÁVEIS DEVERÁ SER ARMAZENADA NA POSIÇÃO SUBSEQUENTE ÀS VARIÁVEIS TESTADAS.
; SE FOREM IGUAIS DEVERÁ SINALIZAR COM O VALOR FFh NA POSIÇÃO 130 OU ARMAZENAR UMA DAS VARIÁVEIS.
; POSIÇÃO 128: PRIMEIRA VARIÁVEL
; POSIÇÃO 129: SEGUNDA VARIÁVEL
; POSIÇÃO 130: MAIOR DAS DUAS VARIÁVEL
; Autor: IGOR GIULIANO
;        GUILHERME CHIQUITO
;        PAULO AUGUSTO
;        MATEUS PORTO
; Data: 30/08/2022
;---------------------------------------------------

X EQU 128 ;
Y EQU 129 ;
Z EQU 130 ;
ORG 0     ;

LDA X     ;
SUB Y     ;

JN  10    ;
JZ  22    ;
JNZ 16    ;

LDA Y     ;
STA Z     ;
JMP 28    ;

LDA X     ;
STA Z     ;
JMP 28    ;

LDA 255   ;
STA Z     ;
JMP 28    ;

OUT 0     ;

HLT       ;